### ISSUE TITLE
Back button doesn't update state

### ISSUE THREAD

**Issue by andrewblaney** [algolia/vue-instantsearch-examples#11]
On pressing back, the url is updated, but the state of the search store isn't updated. I've implemented it the same way as in this app, is there a watcher I can add to refresh the search store on URL change?

Thanks

**Comment by rayrutjes** [comment]
Hey @andrewblaney , could you provide a link to the code sample you are referring to?

**Comment by Haroenv** [comment]
Please open this issue in Vue InstantSearch with a reproducible setup. Thanks!
